# Generated by Django 2.0.2 on 2019-05-23 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_auto_20190523_1054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thread',
            options={'ordering': ['-updated']},
        ),
    ]
